### ISSUE TITLE
Find a better way to reload the new inserted fields

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Form#178]
Right now we are using the completion on batch update to actually update the newly inserted items.
This could be done better!

https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.m#L224

**Comment by NSElvis** [comment]
Link is broken and it points to an invalid place

https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.m#L224

**Comment by zenangst** [comment]
Updated the description.

**Comment by 3lvis** [comment]
I'll just leave the critical issues open, closing this one.
