### ISSUE TITLE
Add support for sending an object as the target value

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Form#185]
It would be nice to be able to send along an entire object of key values for manipulating the target.
This would open up for setting the minimum and maximum dates on fields. This could also help solve the formula and validation manipulation that we aim to support.

**Comment by NSElvis** [comment]
I'm afraid I don't understand, what do you mean by "object of key values"?

Could you provide a sample of the API you would like to have?

**Comment by zenangst** [comment]
```
{
    "id":"target_id",
    "type":"field",
    "action":"update",
    "target_value":{
        "required":true,
        "value": "$other_date_field",
        "minimumDate":"$other_date"
    },
    "condition":"$conditional_value == 2"
 }
```

**Comment by zenangst** [comment]
Also, it would be neat if it supported the `$` delimiter to fetch values from foreign fields

**Comment by NSElvis** [comment]
Looks useful :)

**Comment by zenangst** [comment]
But calling it target_value no longer makes sense.

**Comment by NSElvis** [comment]
Definetly

**Comment by NSElvis** [comment]
I guess you could do

```
{
    "id":"target_id",
    "type":"field",
    "action":"update",
    "required":true,
    "value": "$other_date_field",
    "minimumDate":"$other_date"
    "condition":"$conditional_value == 2"
 }
```

**Comment by fespinoza** [comment]
in that example: if condition is fulfilled then the target_id field will set: a value, a minimun date and make the field required, right?

so the semantic of `target_value` would be like **All the actions that happen when the condition is fulfilled**

**Comment by zenangst** [comment]
@fespinoza something like that yes.

**Comment by fespinoza** [comment]
I prefer the syntax that @zenangst posted, about the field name, can be changed for something like `target_transformations` or something

**Comment by NSElvis** [comment]
A `target` is an element that triggers an action over a `field` or a `section`.

In that idea I think we could bundle all elements into a `target` and make it inherit from a `field`, so it has all the elements of a `field` but with the additional powers.

**Comment by zenangst** [comment]
@NSElvis HYPFormTarget already has a property called `value`.

**Comment by NSElvis** [comment]
@zenangst: naming would just be a detail I guess, everything else should work.

**Comment by 3lvis** [comment]
No new features for now, let's reconsider after the bug fixes have being fixed.
