### ISSUE TITLE
FORMCollectionDataSource as the main point for everything

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/Form#209]

**Comment by NSElvis** [comment]
@zenangst Should we rename `FORMCollectionDataSource` to `FORMController`? Or something like that, since we want it to be the main point to all the Form things?

**Comment by NSElvis** [comment]
This is probably the way you use this class, that's why DataSource made sense

https://github.com/hyperoslo/Form/blob/master/Demos/Basic-ObjC/Basic-ObjC/Controllers/HYPSampleCollectionViewController.m#L42

**Comment by zenangst** [comment]
Yeah I guess it share more of the characteristics of a controller than a data source as it does more than a data source. Was that what you were thinking? Also it shorter, less is more (probably not what she said) :-)

**Comment by NSElvis** [comment]
@zenangst 

This is probably the way you use this class, that's why DataSource made sense, maybe it should be called only `FORMDataSource`

https://github.com/hyperoslo/Form/blob/master/Demos/Basic-ObjC/Basic-ObjC/Controllers/HYPSampleCollectionViewController.m#L42

**Comment by zenangst** [comment]
There is no real added benefit of calling it Collection? or is that hinting to that the Form is a collection view?

**Comment by NSElvis** [comment]
@zenangst It can only be used with a collection, so no need to be redundant with that.

**Comment by zenangst** [comment]
Let's go for `FORMDataSource`, agree?

**Comment by NSElvis** [comment]
@zenangst agreed

**Comment by NSElvis** [comment]
Fixed
