### ISSUE TITLE
Section where fields don't add up to 100 have weird behaviours

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#219]
Example:

First name field => 50 : 1
Last name field => 25 : 1
Image field => 100 : 1.7

**Comment by zenangst** [comment]
@NSElvis mind adding a screenshot?

**Comment by NSElvis** [comment]
@zenangst What should be the behaviour here? Crash and burn?

**Comment by zenangst** [comment]
@NSElvis if the JSON is served up from a backend it could be risky to force a crash, what do you think?

**Comment by NSElvis** [comment]
A crash when parsing the field that is adding up more than 100 and saying "Why?" could be a good solution.

Backends should calculate correct widths, we can't really handle all the scenarios.

What do you think @fespinoza?

**Comment by zenangst** [comment]
Oh sorry.

**Comment by richardoti** [comment]
@zenangst should we close?

**Comment by 3lvis** [comment]
Haven't hard of anyone finding this critical. Closing and let's reopen if this becomes critical.
