### ISSUE TITLE
Remove `strong` from properties since it's the new default

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/Form#230]
All the 

```objc
@property (nonatomic, strong) NSNumber *age;
```

Would be

```objc
@property (nonatomic) NSNumber *age;
```

**Comment by zenangst** [comment]
I just found out that `strong` as been the default since Xcode 4.3, so it's not really new.

**Comment by markvaldy** [comment]
Agree, looks more clear without ``strong``

**Comment by markvaldy** [comment]
Could we add it to iOS-playbook as well if everyone agrees?

**Comment by NSElvis** [comment]
@markvaldy Added it as an issue

https://github.com/hyperoslo/iOS-playbook/issues/42
