### ISSUE TITLE
iOS 8 warnings for some dependencies

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#254]
![screen shot 2015-03-17 at 8 03 52 am](https://cloud.githubusercontent.com/assets/1088217/6682666/38122566-cc7c-11e4-9eaf-dc30212ee142.png)

**Comment by kostiakoval** [comment]
@NSElvis use my repo. I've fixed it
pod 'iso-8601-date-formatter', :git=> https://github.com/kostiakoval/iso-8601-date-formatter.git

**Comment by NSElvis** [comment]
Thanks!

**Comment by 3lvis** [comment]
haven't seen this again
