### ISSUE TITLE
Store removed dynamic values in a property on FORMDataSource

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Form#258]
When you press `Remove` in a dynamic section, all the values that share the same prefix as that section should be stored in a property on `FORMDataSource`. These keys should also be remove from `valuesDictionary` inside `FORMDataSource`.

**Steps to reproduce**

1. Press delete on dynamic company 0 (name: Facebook)

**Current results**

1. `FORMData.removedDynamicValues` doesn't contain `company[0].name = Facebook`
2. `FORMData.valuesDictionary` contains `company[0].name = Facebook`

**Expected results**

1. `FORMData.removedDynamicValues` contains `company[0].name = Facebook`
2. `FORMData.valuesDictionary` no longer contains `company[0].name = Facebook`

**Comment by NSElvis** [comment]
- Removed `company[3]`
- All items prefixed with `company[3]` get added as `company[0]` if `removedDynamicValues` is empty.

`removedDynamicValues` is a dictionary

**Comment by zenangst** [comment]
Started a pull request for this - https://github.com/hyperoslo/Form/pull/260

**Comment by zenangst** [comment]
Should it sanitize the indexes in `valuesDictionary` after removing them?
So that removing `company[3]` would make `company[4]` into `company[3]`.

**Comment by NSElvis** [comment]
I think we talked about this but yeah, that would be awesome!

**Comment by zenangst** [comment]
Working on it now ;)
