### ISSUE TITLE
README 2.0

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#271]
I've been thinking on improving the README to showcase our biggest features and have a banner for each:

- [ ] Targets
- [ ] Formulas
- [ ] Templates
- [ ] Customization
- [ ] Formatters
- [ ] Validators

**Comment by NSElvis** [comment]
@zenangst is there anything else to add?

**Comment by NSElvis** [comment]
I'm still unsure if the naming is clear enough, would love to get your feedback @hyperoslo/ios

**Comment by zenangst** [comment]
Customization might be nice to mention so that people don't perceive it to be locked to a specific design.

**Comment by NSElvis** [comment]
@zenangst agreed! Updated

**Comment by zenangst** [comment]
Is Formatters worth mentioning ?

**Comment by NSElvis** [comment]
Formatters and validators!

**Comment by zenangst** [comment]
So many things...

**Comment by 3lvis** [comment]
Closing down, let's reconsider if a Swift rewrite ever happens.
