### ISSUE TITLE
address field example

### ISSUE THREAD

**Issue by yasirmturk** [hyperoslo/Form#276]
how to create a multi-input field like address field in iOS Contacts App

**Comment by NSElvis** [comment]
Hi @yasirmturk, we've been planning on add more domain specific examples, the one you pointed our is on top of our list.

I think you could get what you need from here: https://github.com/hyperoslo/Form/tree/master/Demos/Basic-ObjC

It's a bit more general but it could help you to get started.

Let me know if something is not clear :)

**Comment by NSElvis** [comment]
@yasirmturk: Let me know if we can help with something else. 

I'll be closing this issue for now.
