### ISSUE TITLE
Force UICollection to refresh on validation

### ISSUE THREAD

**Issue by matteocrippa** [hyperoslo/Form#283]
I noticed playing with demo app that sometimes the code fails on showing invalid fields, I simply managed to force in the main queue to update the collection with something like

```
dispatch_async(dispatch_get_main_queue(), ^
                   {
                       [self.collectionView reloadData];

                   }); 
```

Prob it will needed even when the user scroll in order to check for fields that during validation are out of viewport.

**Comment by NSElvis** [comment]
We'll take a look! Thanks @matteocrippa :dancers:

**Comment by 3lvis** [comment]
This has been fixed.
