### ISSUE TITLE
Form crashes on iPhone. 

### ISSUE THREAD

**Issue by kostiakoval** [hyperoslo/Form#311]
The popup is not available on iPhone.
-[UIPopoverController initWithContentViewController:] called when not running under UIUserInterfaceIdiomPad.'

**Comment by 3lvis** [comment]
Thanks <3

**Comment by danr777** [comment]
How can we fix this? use the new ios8+ popover object?

**Comment by 3lvis** [comment]
@danr777 Yeah! That might work

**Comment by richardoti** [comment]
Now it doesn't.
But design should be improved later, as fullscreen tableview doesn't looks good.
