### ISSUE TITLE
Add image and arrow to FORMHeader

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#313]
Would be nice to have support for icons and arrows like this ones.

![dwqdqw](https://cloud.githubusercontent.com/assets/1088217/7042178/401c8c7c-dde0-11e4-97ef-c9b3ddfcc728.png)

**Comment by zenangst** [comment]
Those are some nice titles you got there;

![tumblr_n50qd2rp8x1qdlh1io1_400](https://cloud.githubusercontent.com/assets/57446/7042267/e7773c06-dde0-11e4-8c22-44eeb4da25ed.gif)

**Comment by 3lvis** [comment]
Hahaha

**Comment by RyanKim01** [comment]
@3lvis , Do you mind letting me know how this is going? I'm ultimately looking for a way to either put a check mark on the group title or change color of text on the group title so I can inform users they are done with this section. This feature is exactly what I'm looking for so I'm wondering if there is any progress in this :)

**Comment by 3lvis** [comment]
@RyanKim01 Hi! This is just a decoration arrow, might not help in what you're looking for. But you have a great use case! We should definitely consider supporting something like that.

**Comment by RyanKim01** [comment]
@3lvis oops. I totally read this wrong lol Can you think of any way which can make either one possible depends on validation state in textfields now? Or do you think this is something needs to be more discussed and implemented.

**Comment by 3lvis** [comment]
I think the datasource would have to inform Form to update the decoration.

**Comment by 3lvis** [comment]
Not critical for now, I'll close it down unless someone else thinks this is useful.
