### ISSUE TITLE
Json Key to default hide a field

### ISSUE THREAD

**Issue by matteocrippa** [hyperoslo/Form#317]
Is there already any json key in order to set a field hidden by default?

**Comment by 3lvis** [comment]
Hi @matteocrippa, at the moment you can send a [hideFieldTarget](https://github.com/hyperoslo/Form/blob/f6b812617f6c1df5abf6223210d01a6299b84835/Source/Models/FORMTarget.h#L43) to hide the field.

We don't have support for adding a flag in the JSON that says `hidden: true;` but we should totally have that! 

I'll make an issue for it.
