### ISSUE TITLE
Mark fields as initially hidden in the JSON

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#318]
Would be great if you could mark a field as hidden by adding a "hidden" flag to the field's json.

```json
{
  "id": "first_name",
  "hidden": true
}
```

References #317

**Comment by matteocrippa** [comment]
got it, plan to push tonight the solution

**Comment by 3lvis** [comment]
Released on 3.0.2 => https://github.com/hyperoslo/Form/releases/tag/3.2.0

Thanks for your contribution @matteocrippa, you are awesome!
