### ISSUE TITLE
Minimum & Maximum Value

### ISSUE THREAD

**Issue by charbelhass** [hyperoslo/Form#324]
Hello,
how can i set a minimum or a maximum value for a text of input-type number.
is it implemented?

thanks in advance,
regards

**Comment by 3lvis** [comment]
Hi,

You'll have to add it to your `validations` dictionary in the field JSON.

In our basic demo we have a `first_name` field that supports minimum length 2. So when you call "validate" if this field has less than 2 characters it will show up red.

https://github.com/hyperoslo/Form/blob/d426e7b090fee7a630d1208b87c63a85b6aaf5df/Demos/Basic-ObjC/Basic-ObjC/Assets/forms.json#L19-L22

**Comment by charbelhass** [comment]
@3lvis thanks, the value i want to enter is a number. I can't see how can i solve it with length
i have 3 options:
-the number must be between 2 other numbers like 10 < inputvalue < 20
-the number is greater than other one like inputvalue > 30
-the number is less than other one like inputvalue < 30

**Comment by 3lvis** [comment]
You can do `max_value` and `min_value` too.

https://github.com/hyperoslo/Form/blob/master/Source/Models/FORMFieldValidation.m#L24 

:)

**Comment by charbelhass** [comment]
thanks :D

**Comment by charbelhass** [comment]
@3lvis sorry for bothering you, i have been trying for a while to do the min and max value for text of input type number nothing is happening, when i try to enter a number less than the min value and press validate, the field show that it is valid
this is my code:
if (![question[@"MinimumValue"] isKindOfClass:[NSNull class]] && ![question[@"MaximumValue"] isKindOfClass:[NSNull class]])
                {
                    title = [title stringByAppendingString:[NSString stringWithFormat:@" (Min: %d, Max: %d)", [question[@"MinimumValue"] intValue], [question[@"MaximumValue"] intValue]]];
                    NSInteger minvalue = [question[@"MinimumValue"] integerValue];
                    NSInteger maxvalue = [question[@"MaximumValue"] integerValue];
                    [dicValidation setValue:[NSNumber numberWithInteger:minvalue] forKey:@"min_value"];
                    [dicValidation setValue:[NSNumber numberWithInteger:maxvalue] forKey:@"max_value"];
                }
                if ([question[@"MinimumValue"] isKindOfClass:[NSNull class]] && ![question[@"MaximumValue"] isKindOfClass:[NSNull class]])
                {
                    title = [title stringByAppendingString:[NSString stringWithFormat:@" (Max: %d)", [question[@"MaximumValue"] intValue]]];
                    NSInteger maxvalue = [question[@"MaximumValue"] integerValue];
                    [dicValidation setValue:[NSNumber numberWithInteger:maxvalue] forKey:@"max_value"];
                }
                if (![question[@"MinimumValue"] isKindOfClass:[NSNull class]] && [question[@"MaximumValue"] isKindOfClass:[NSNull class]])
                {
                    title = [title stringByAppendingString:[NSString stringWithFormat:@" (Min: %d)", [question[@"MinimumValue"] intValue]]];
                    NSInteger minvalue = [question[@"MinimumValue"] integerValue];
                    [dicValidation setValue:[NSNumber numberWithInteger:minvalue] forKey:@"min_value"];
                }





and this is the generated JSON:

{  
   "groups":[  
      {  
         "id":20140730151130500,
         "title":"Competitors Log",
         "sections":[  
            {  
               "id":"sec1",
               "fields":[  
                  {  
                     "input_type":"number",
                     "size":{  
                        "width":"100",
                        "height":"1"
                     },
                     "type":"text",
                     "id":"1",
                     "validations":{  
                        "min_value":10,
                        "min_length":1,
                        "format":"(?<![-.])\\b[0-9]+\\b(?!\\.[0-9])",
                        "required":"true"
                     },
                     "disabled":"false",
                     "title":"Activity Type (Min: 10) **"
                  }
               ]
            },
            {  
               "id":"sec2",
               "fields":[  
                  {  
                     "type":"text",
                     "id":"2",
                     "disabled":"false",
                     "title":"Date of Activity **",
                     "size":{  
                        "width":"100",
                        "height":"1"
                     },
                     "validations":{  
                        "min_length":1,
                        "required":"true"
                     }
                  }
               ]
            },
            {  
               "id":"sec3",
               "fields":[  
                  {  
                     "type":"text",
                     "id":"3",
                     "disabled":"false",
                     "title":"Topic of the Activity **",
                     "size":{  
                        "width":"100",
                        "height":"1"
                     },
                     "validations":{  
                        "min_length":1,
                        "required":"true"
                     }
                  }
               ]
            },
            {  
               "id":"sec4",
               "fields":[  
                  {  
                     "input_type":"number",
                     "size":{  
                        "width":"100",
                        "height":"1"
                     },
                     "type":"text",
                     "id":"4",
                     "validations":{  
                        "required":"false",
                        "min_value":2,
                        "format":"(?<![-.])\\b[0-9]+\\b(?!\\.[0-9])",
                        "max_value":32
                     },
                     "disabled":"false",
                     "title":"Speaker (Min: 2, Max: 32)"
                  }
               ]
            },
            {  
               "id":"sec5",
               "fields":[  
                  {  
                     "type":"text",
                     "id":"5",
                     "disabled":"false",
                     "title":"Targeted Products",
                     "size":{  
                        "width":"100",
                        "height":"1"
                     },
                     "validations":{  
                        "required":"false"
                     }
                  }
               ]
            },
            {  
               "id":"sec6",
               "fields":[  
                  {  
                     "type":"text",
                     "id":"7",
                     "disabled":"false",
                     "title":"Additional Comments and observations",
                     "size":{  
                        "width":"100",
                        "height":"1"
                     },
                     "validations":{  
                        "required":"false"
                     }
                  }
               ]
            }
         ]
      }
   ]
}
