### ISSUE TITLE
Feature: Time picker fields

### ISSUE THREAD

**Issue by Mutix** [hyperoslo/Form#332]
What do you guys think would be the best approach for adding the ability to select time?

I was thinking it could be useful to have three different field types: 'date', 'date_time', and 'time', where:

- 'date' is the existing date type that shows a datepicker popover with only the day, month and year components
- 'date_time' would show a datepicker popover with all components (day, month, year, hours, minutes, ~AM/PM)
- 'time' would show datepicker popover with only the time components (hours, minutes, ~AM/PM)

This could be achieved by leveraging the existing `FORMDateFieldCell`, all three field types could use the `FORMDateFormFieldCellIdentifier`:

https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.m#L150

and we could change the UIDatePicker's `datePickerMode` depending on the field type in the dateFieldCell's `updateContentViewController: withField:` method?

https://github.com/hyperoslo/Form/blob/master/Source/Cells/Popover/FORMDateFieldCell.m#L104

What do you think?

**Comment by 3lvis** [comment]
Hi @Mutix!

Thanks a lot for such detailed issue. Using an additional field type sounds very interesting, at the moment we only do dates in our apps and this sounds like a very useful feature.

For the pod user I guess the old the thing it would change would be the field type, everything else would keep been transparent.

I say :+1: great job!

**Comment by Mutix** [comment]
Thanks 3lvis,

I've just done some work on this in my fork, and am nearly ready to issue a pull request, will comment on here with the link to the PR when it's ready :)

**Comment by zenangst** [comment]
:+1:

**Comment by Mutix** [comment]
https://github.com/hyperoslo/Form/pull/333

:+1:

**Comment by 3lvis** [comment]
Fixed on #333, will be available on the next release

**Comment by 3lvis** [comment]
Great job @Mutix! 
![tumblr_inline_mzmuzndcac1qi4qb3](https://cloud.githubusercontent.com/assets/1088217/7187343/21c04a98-e470-11e4-817a-af133f90cd01.gif)
