### ISSUE TITLE
Add support for secure entry text fields (eg. passwords)

### ISSUE THREAD

**Issue by Mutix** [hyperoslo/Form#345]
Would be awesome to have a new 'secure' field type which would set  `secureTextEntry` to true on the UITextField.

The login demo app can then use this new type for the password field.

Will start a branch in my fork :)

**Comment by 3lvis** [comment]
Hi @Mutix!

We were considering this! I think a field type `password` would do.

**Comment by Mutix** [comment]
Perfect, have you already started this or shall I?

**Comment by zenangst** [comment]
@Mutix go ahead :)

**Comment by Mutix** [comment]
:+1:

**Comment by Mutix** [comment]
@3lvis @zenangst Sorry I just realised this is already supported via `"input_type":"password"`..

**Comment by 3lvis** [comment]
:O

**Comment by 3lvis** [comment]
@Mutix should we close this issue then?

**Comment by Mutix** [comment]
@3lvis I'm just updating the Login demo app to use the password input_type then yes I guess we can close the issue :)
