### ISSUE TITLE
Add ability to set custom bounds for forms which are not full-screen

### ISSUE THREAD

**Issue by Mutix** [hyperoslo/Form#350]
Currently, the bounds used by the form layout are the main screen's bounds.

If we attempt to present a form in a modal form sheet presentation style on the iPad, the form layout is wrong and the width for groups, sections and fields end up being too large for the reduced view size.

For example:

![ios simulator screen shot 17 apr 2015 14 08 21](https://cloud.githubusercontent.com/assets/677629/7202540/3a900590-e50b-11e4-9b66-5b1b4dc19267.png)

 
A potential solution could be exposing a `formBounds` property in the FORMLayout class, and using this instead of the main screen bounds for calculating sizes.

A new `initWithFormBounds:` initialiser could also be added.

Any thoughts on how best to implement this?

**Comment by 3lvis** [comment]
Woah, did saw this one. I think you can use the UICollectionView's bounds for this.

**Comment by Mutix** [comment]
:+1: Using the collection view's bounds makes most sense indeed.

PR incoming shortly :)
