### ISSUE TITLE
Field icons (date, down arrow, clock) overlap field's text field if the field's width is short

### ISSUE THREAD

**Issue by Mutix** [hyperoslo/Form#351]
As seen in this example:

![ios-simulator-screen-shot-17-apr-2015-15 02 28](https://cloud.githubusercontent.com/assets/677629/7203529/2cd20964-e513-11e4-8037-bb7bf21bc7f4.png)

**Comment by 3lvis** [comment]
Hi @Mutix,

Not sure if we could/should do something about this, it's up to the developer to find a field size that fits the screen.

If you think otherwise please let me know.

**Comment by Mutix** [comment]
Agreed, it is the client's responsibility to choose an appropriate layout for the form (I changed the layout in the modal form example because of this). 

It could be handled a bit more gracefully though (for example not showing the icon if there isn't enough space for it), but happy for the issue to be closed for now :)
