### ISSUE TITLE
How To Get Entered Values

### ISSUE THREAD

**Issue by charbelhass** [hyperoslo/Form#352]
Hello,
I created all the fields i want, i can't figure out how to get the results after filling the fields!

Thanks

**Comment by 3lvis** [comment]
Hi @charbelhass! 

You can get the values from your `FORMDataSource` instance by calling `values` => https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.h#L139

```objc
NSDictionary *valuesDictionary = [self.dataSource values];
```

**Comment by charbelhass** [comment]
yeah thanks :D
