### ISSUE TITLE
Dynamic section inserts new section at the end when it should be just before the add button

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#373]
- First name field
- Add button
### Pressed add button

_Current:_
- First name field
- Add button
- New dynamic field 1

_Expected:_
- First name field
- New dynamic field 1
- Add button
### Pressed add button

_Current:_
- First name field
- Add button
- New dynamic field 1
- New dynamic field 2

_Expected:_
- First name field
- New dynamic field 1
- New dynamic field 2
- Add button

**Comment by 3lvis** [comment]
@thuygianguyen is this correct?

**Comment by zenangst** [comment]
Seems correct as far as I know.
