### ISSUE TITLE
Edit the value of a form field

### ISSUE THREAD

**Issue by jeffleeismyhero** [hyperoslo/Form#385]
I will be reading input from hardware and would like the data to appear, as it is read, in a form field.

Is this currently possible? I've tried the following, but the form field never visually updates.

```objective-c
- (void)updateButtonAction {
    NSLog(@"Update Pressed");
    [self.dataSource fieldWithID:@"debug-data" includingHiddenFields:YES
    completion:^(FORMField *field, NSIndexPath *indexPath) {
      if (field) {
        field.value = @"debug data here";
        [self.dataSource didChangeValueForKey:field.fieldID];
        [self.dataSource reloadFieldsAtIndexPaths:@[indexPath]];
        [self.collectionView reloadItemsAtIndexPaths:@[indexPath]];
      }
    }];
}
```

**Comment by 3lvis** [comment]
Hi @jeffleeismyhero,

You can use `[self.dataSource reloadWithDictionary:@{"debug-data" : @"debug data here"}];`

https://github.com/hyperoslo/Form/blob/master/Demos/Basic-ObjC/Basic-ObjC/Controllers/HYPSampleCollectionViewController.m#L202-L210

Please let me know if this works for you :)

**Comment by jeffleeismyhero** [comment]
Yes, thanks. I just got that working. I tried it before but did not call reloadData on the collection view.

```objective-c
- (void)updateButtonAction {
    NSLog(@"Update Pressed");
    [self.dataSource reloadWithDictionary:@{@"debug_data" : @"Debug Data..."}];
    [self.collectionView reloadData];
}
```
