### ISSUE TITLE
Module 'HYPMathParser' not found

### ISSUE THREAD

**Issue by jeffleeismyhero** [hyperoslo/Form#409]
I'm receiving the following error when I attempt to use the current master branch (d2b80b982adc90e428817d02f7ce62067bf9a8cd):

```
... Pods/Form/Source/Others/DDMathEvaluator+FORM.h:1:9: Module 'HYPMathParser' not found
```

**Comment by 3lvis** [comment]
Have you try using

`use_frameworks!` in your Podfile?

**Comment by jeffleeismyhero** [comment]
Thanks, that was it.
