### ISSUE TITLE
UIButton highlight state not working with Form installed

### ISSUE THREAD

**Issue by uzegonemad** [hyperoslo/Form#415]
I'm sure that I'm just missing something but when I install Form, the highlighted state on UIButtons cease to work.

I've whipped up [a demo](https://github.com/uzegonemad/hyperoslo-form-uibutton-issues) detailing this issue, but here are the steps to recreate:

1. Create a new project
1. Install form (in this case via pods)
1. Add button to storyboard
1. Add outlet
1. Add code to set title color on highlight
1. ???

When you tap (and hold) on the button, it should turn green, but it stays blue. Even without setting the highlighted color, the button tint does not change on highlight with Form installed.

**Comment by 3lvis** [comment]
@uzegonemad Hi Benjamin, thanks for reporting this issue, I'll let you know what I find.

Best,

**Comment by uzegonemad** [comment]
@3lvis thank you! Let me know if there's anything else I can do to assist.

**Comment by uzegonemad** [comment]
I tracked this down to a [couple lines](https://github.com/3lvis/UIButton-ANDYHighlighted/blob/99c1d3ebfcdc9d1b4add507e8cb5ba8a3d575627/Source/UIButton%2BANDYHighlighted.m#L69-L83) from `UIButton-ANDYHighlighted`. The specific method I'm referring to is `setHighlighted`.

As a test, I commented out that method in my example and the highlighted state began functioning as expected.

Then, I opened Form's Basic-ObjC example, commented out the method, and the button highlight states on the form stopped working.

So... it seems like a catch 22.

Would you be opposed to subclassing UIButton instead of using a category to override the highlighted state? That way the highlight code would be isolated, and then highlights would potentially work for both standard controls and the form controls. Because of the way objective-c works, this category gets triggered globally regardless of if it's imported or not, meaning it will affect all buttons - not just those implemented in Form.

**Comment by 3lvis** [comment]
@uzegonemad Wow, this could definitely be an issue, also I remember someone saying that you have to set all the three properties of highlighted button in order to get it working.

https://github.com/3lvis/UIButton-ANDYHighlighted/blob/master/Source/UIButton%2BANDYHighlighted.h#L5-L9

I always added a color to all the properties I guess that's why I got it working without problems.

**Comment by 3lvis** [comment]
@uzegonemad Can you try using the `FORMDefaultStyle` to check if the error still appears, as I wrote before having I remember someone saying that you need to have all of this ones:

```objc
[[FORMButtonFieldCell appearance] setBackgroundColor:[UIColor colorFromHex:@"3DAFEB"]];
[[FORMButtonFieldCell appearance] setHighlightedTitleColor:[UIColor colorFromHex:@"3DAFEB"]];
[[FORMButtonFieldCell appearance] setBorderColor:[UIColor colorFromHex:@"3DAFEB"]];
[[FORMButtonFieldCell appearance] setHighlightedBackgroundColor:[UIColor whiteColor]];
[[FORMButtonFieldCell appearance] setTitleColor:[UIColor whiteColor]];
```

In order to button change color properly.

**Comment by uzegonemad** [comment]
@3lvis I tried using both `FORMDefaultStyle` and manually setting the appearance, still nothing.

I'm curious why the super method isn't getting called though - seems like that portion is an Apple bug. Even if you comment out the if statements and _only_ call the super method, it still doesn't trigger. This is very bizarre!

**Comment by 3lvis** [comment]
Hi @uzegonemad, I cloned your example and this is definitely an issue with the UIButton category that we use in Form.

You can achieve the highlighting colors using

```
self.superAwesomeButton.titleColor = [UIColor blueColor];
self.superAwesomeButton.highlightedTitleColor = [UIColor greenColor];
```

**Comment by 3lvis** [comment]
I moved this issue to the respective project. => https://github.com/3lvis/UIButton-ANDYHighlighted/issues/3

Please let me know if the workaround doesn't work for you.

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/Form/issues/416
