### ISSUE TITLE
Multi-select Branch

### ISSUE THREAD

**Issue by jeffleeismyhero** [hyperoslo/Form#425]
What is the status of merging in the [feature/multiselect](https://github.com/hyperoslo/Form/tree/feature/multiselect) branch?

**Comment by 3lvis** [comment]
Hey @jeffleeismyhero, that branch is death. You can follow progress here => https://github.com/hyperoslo/Form/issues/242

The current status of this feature is:

>No progress coming soon; feel free to send a PR following the suggested design. :)
