### ISSUE TITLE
field height?

### ISSUE THREAD

**Issue by danr777** [hyperoslo/Form#426]
I am not clear how to work this?

"size":{
                "width":100,
                "height":???
              },

Does not seem to have an effect on a text field at all?

Is there a multiline text option?

Thanks in advance!

**Comment by 3lvis** [comment]
Hi Dan,

The `height` only affects custom fields, for example in the [Basic-Objc demo](https://github.com/hyperoslo/Form/tree/master/Demos/Basic-ObjC) you have an `image` cell. Changing the height:

```
{
  "id":"image",
  "type":"image",
  "size":{
    "width":100,
    "height":5
  },
  "hidden":true
}
```
Makes it look like this

![simulator screen shot jun 18 2015 7 14 02 pm](https://cloud.githubusercontent.com/assets/1088217/8237315/a52ec51c-15ee-11e5-9360-a8248d7c98c8.png)

**Comment by 3lvis** [comment]
@danr777 We don't have support for multiline text option, you can add your own following the patterns used for the custom `image` field.

**Comment by 3lvis** [comment]
@danr777 This is where we set the height of the fields

https://github.com/hyperoslo/Form/blob/eed1f04d63dbecf0e4a62993f4f7150a20847fdd/Source/FORMDataSource.m#L288-L292

**Comment by danr777** [comment]
thank you!:)
