### ISSUE TITLE
Custom Field value storage?

### ISSUE THREAD

**Issue by danr777** [hyperoslo/Form#428]
As an example in the "image" custom field, how would one set a value back to the datasource of the form itself?

**Comment by 3lvis** [comment]
@danr777 Make it a subclass of `FORMBaseFieldCell` and when the value changes you can call the delegate:

```objc
    if ([self.delegate respondsToSelector:@selector(fieldCell:updatedWithField:)]) {
        [self.delegate fieldCell:self
                updatedWithField:self.field];
    }
```

This will inform `FORMDataSource` of the change.

[This is how `FORMTextFieldCell` does it](https://github.com/hyperoslo/Form/blob/master/Source/Cells/Text/FORMTextFieldCell.m#L332-L345)

**Comment by 3lvis** [comment]
@danr777 are you working on the multi-line field? I might be able to help :)

**Comment by danr777** [comment]
Hi,  Yeah, I give up lol... I tried as an experiment, just changing UITextField to UITextField on the TextField.m's and TextFieldCells.m, but could not figure out one error.. but now i think i'll just make a custom one, now with this It will help ..

I have a whole bunch of custom fields i'd like to make now with this information

Map location selector, Signature collection, Multiselect, multi photo browser w/ in cell preview of all attached thumbnails (in a scrollview)

**Comment by 3lvis** [comment]
@danr777 hahaha, wow, all of that sounds nice. How would the map location selector work?

**Comment by danr777** [comment]
Show a mkmapview which would a default location with one pin in center.
That mkannotation would be draggable

**Comment by danr777** [comment]
Or even nicer there would a stationary crosshair overlay on map and as you
drag/zoom the map around the crosshair would always stay dead center

**Comment by 3lvis** [comment]
@danr777 Interesting!

**Comment by danr777** [comment]
Just not getting it, that line never gets past the first condition: (sorry! thank you for help!!! :) ), i'm sure once I see a working example i'll figure it out:, basically want my textview.text to be my value stored 

```
#import "FORMBaseFieldCell.h"

static NSString *const FORMCustomMultilineCellIdentifier = @"FORMCustomMultilineCellIdentifier";
interface FORMCustomMultilineCell : FORMBaseFieldCell <UITextViewDelegate>

@end

#import "FORMCustomMultilineCell.h"
#import "UIColor+Hex.h"

@implementation FORMCustomMultilineCell

#pragma mark - Initializers

- (instancetype)initWithFrame:(CGRect)frame {
	self = [super initWithFrame:frame];
	if (!self) return nil;
	self.contentView.backgroundColor = [UIColor whiteColor];
	
	self.contentView.layer.cornerRadius = 5.0f;
	self.contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
	
	[self.contentView addSubview:[self container]];
	
	return self;
}

- (void)textViewDidChange:(UITextView *)textView {
	if ([self.delegate respondsToSelector:@selector(fieldCell:updatedWithField:)]) {
		[self.delegate fieldCell:self
		        updatedWithField:self.field];
	}
}

- (void)updateWithField:(FORMField *)field {
	[super updateWithField:field];
}

- (UILabel *)myLabel {
	CGRect labelFrame = CGRectMake(10, 0, CGRectGetWidth(self.frame) - 60, 44);
	UILabel *label = [[UILabel alloc] initWithFrame:labelFrame];
	label.font = [UIFont fontWithName:@"AvenirNext-DemiBold" size:14.0];
	label.textColor = [UIColor colorFromHex:@"28649C"];
	label.text = @"Main title";
	return label;
}

- (UITextView *)myTextView {
	UITextView *textView = [[UITextView alloc] initWithFrame:CGRectMake(10, 48, CGRectGetWidth(self.frame) - 39, CGRectGetHeight(self.frame) - 100)];
	textView.delegate = self;
	textView.contentInset = UIEdgeInsetsMake(2, 2, 2, 2);
	textView.layer.borderWidth = 1.0f;
	textView.layer.borderColor = [[UIColor colorFromHex:@"3DAFEB"] CGColor];
	textView.layer.cornerRadius = 5.0f;
	textView.backgroundColor = [UIColor colorFromHex:@"C0EAFF"];
	return textView;
}

- (UIView *)container {
	UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0.0f, 0.0f, CGRectGetWidth(self.frame), CGRectGetHeight(self.frame))];
	[view addSubview:[self myLabel]];
	[view addSubview:[self myTextView]];
	return view;
}

#pragma mark - Layout

- (void)layoutSubviews {
	[super layoutSubviews];
	
	self.contentView.frame = [self contentViewFrame];
}

- (CGRect)contentViewFrame {
	CGRect frame = self.frame;
	frame.origin.x = 0;
	frame.origin.y = 0;
	frame.size.width = CGRectGetWidth(self.frame);
	frame.size.height = CGRectGetHeight(self.frame);
	return frame;
}

@end

```

**Comment by 3lvis** [comment]
@danr777 Sorry, I was wrong, you'll have to use a different method to notify FORMDataSource of your changes. I'm working on improving support for custom fields using the multiline as an example.

**Comment by danr777** [comment]
Wow that’s great! Thank you

**Comment by rengarajuram** [comment]
Hi Elvis Nuñez,
I tried to  integrate UITextview in this script, but i couldn't get the result. can you post the sample code for UITextView using custom fields.

**Comment by 3lvis** [comment]
@rengarajuram I'll make an issue for it :)

**Comment by 3lvis** [comment]
@rengarajuram @danr777 sorry that this took too long, here you go.

https://github.com/hyperoslo/Form/pull/453

**Comment by rengarajuram** [comment]
Thank you Elvis Nuñez.
