### ISSUE TITLE
Initialize all collapsed

### ISSUE THREAD

**Issue by jeffreyjackson** [hyperoslo/Form#432]
Is there current functionality to initialize all groups collapsed?

**Comment by zenangst** [comment]
@jeffreyjackson hey, no not at the moment but feel free to make a pull request and add it :sunglasses:

**Comment by jeffleeismyhero** [comment]
:+1 on that PR. It would also be nice to have a way to programmatically collapse a specific group. Or documentation if a way already exists.

**Comment by zenangst** [comment]
@jeffleeismyhero :+1: on that suggestion!

**Comment by jeffreyjackson** [comment]
See PR #433
