### ISSUE TITLE
FORMDataSource.m

### ISSUE THREAD

**Issue by Jamonek** [hyperoslo/Form#439]
Around line 166:
```
case FORMFieldTypeCount:
            identifier = FORMTextFieldCellIdentifier;
            break;
case FORMFieldTypeCount:
            identifier = FORMCountFieldCellIdentifier;
            break;
```
What should the second case be?

I ran into a compile issue with this.

**Comment by 3lvis** [comment]
@Jamonek Shouldn't be needed was introduced in the last PR, I'll look into it

**Comment by 3lvis** [comment]
Fixed https://github.com/hyperoslo/Form/commit/d81e57eeb5cb56fdd3d79f313be00576ed1134aa
