### ISSUE TITLE
Build error after install with pods

### ISSUE THREAD

**Issue by philipheinser** [hyperoslo/Form#440]
```
/.../Pods/Form/Source/Others/DDMathEvaluator+FORM.h:9:9: 'DDMathEvaluator.h' file not found
```

**Comment by 3lvis** [comment]
Hi Philip!

Are you using `use_frameworks!` on your Podfile?

**Comment by philipheinser** [comment]
My Podfile :
```
use_frameworks!

pod 'Form'

```

**Comment by philipheinser** [comment]
@3lvis how can this be? ```pods install``` does run successfully.

**Comment by richardoti** [comment]
I remember, I had the same issue. What CocoaPods version did you use?

**Comment by 3lvis** [comment]
>Now it's no longer reproducible.
