### ISSUE TITLE
Scroll to a section automatically?

### ISSUE THREAD

**Issue by uzegonemad** [hyperoslo/Form#442]
Is it possible to scroll to a specific section (and/or field) when a button is tapped?

I'm building a form with many sections and would like the ability to add a "Table of Contents" view off to the side. This would contain buttons for all the sections in my form, and tapping the button would scroll to the specific section.

As a crude example, let's say I have a form with five sections: Purple, Blue, Green, Blue, Orange.

Ideally, I'll have five buttons somewhere else on the screen (dynamically generated from on the form's sections). When I tap my "Blue" button, the form should scroll to that specific section.

Thanks!

**Comment by jeffleeismyhero** [comment]
There doesn't seem to be a method to do that currently; however, the method used to insert dynamic sections has similar behavior.

https://github.com/hyperoslo/Form/blob/eed1f04d63dbecf0e4a62993f4f7150a20847fdd/Source/FORMData.m#L1145

You may be able to modify the segment below from:

```objective-c
- (void)insertTemplateSectionWithID:(NSString *)sectionTemplateID
                 intoCollectionView:(UICollectionView *)collectionView
                         usingGroup:(FORMGroup *)group
```

to accomplish the task:

```objective-c
if (collectionView) {
    [self sectionWithID:section.sectionID completion:^(FORMSection *section, NSArray *indexPaths) {
        if (indexPaths) {
            [collectionView insertItemsAtIndexPaths:indexPaths];

            [collectionView scrollToItemAtIndexPath:indexPaths.lastObject
                                   atScrollPosition:UICollectionViewScrollPositionTop
                                           animated:YES];
        }
    }];
}
```

**Comment by 3lvis** [comment]
@jeffleeismyhero you are fantastic! 

I think that's right you can just use the method to retrieve the indexPath of the section that you want and scroll to it.

```objc
    [self sectionWithID:@"purple" completion:^(FORMSection *section, NSArray *indexPaths) {
        if (indexPaths) {
            [collectionView scrollToItemAtIndexPath:indexPaths.firstObject
                                   atScrollPosition:UICollectionViewScrollPositionTop
                                           animated:YES];
        }
    }];
```
