### ISSUE TITLE
Better storyboard support

### ISSUE THREAD

**Issue by richardoti** [hyperoslo/Form#448]
In storyboard it is possible to specify class for the ViewController:
![screen shot 2015-08-27 at 22 15 45](https://cloud.githubusercontent.com/assets/8013017/9532483/415e1498-4d0c-11e5-9549-77fa667463bc.png)
It would be nice to be able to specify CollectionViewLayout class and not to do that in code, as we have to right now. This way we could avoid such a bugs: #444 
![screen shot 2015-08-27 at 22 16 47](https://cloud.githubusercontent.com/assets/8013017/9532517/6d47d8f0-4d0c-11e5-9f43-6697a6498147.png)

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/Form/pull/487

**Comment by 3lvis** [comment]
I gave it a try and the solution is so ugly. We would have to make some private properties public. This makes Form less immutable and more prone to errors. There's no reason why you couldn't keep using Storyboards or Interface builder and at the same time use Form programatically.

Example: https://github.com/hyperoslo/Form/blob/master/ModalForm/ViewController.swift#L6-L7

Full project: https://github.com/hyperoslo/Form/blob/master/ModalForm
