### ISSUE TITLE
Better iPhone "Popover" view

### ISSUE THREAD

**Issue by richardoti** [hyperoslo/Form#452]
When I've added iPhone support for popovers, I've just upgraded the logic to new iOS8 features. UI hasn't changed on iPad at all, but on iPhone modal popovers do not look good as some parts of the content interfere with the status bar.

I think, this should be fixed and the best solution is to avoid any phone/tablet specific code, but to use methods provided by Apple.

At first, I think, it may be good idea to embed tableview into navigation controller and to use "cancel/save" buttons as Apple does. Then we would not have any problems with layout on iPhone. This should be easy and Im going to take care about it quite soon.
![screen shot 2015-08-31 at 04 14 33](https://cloud.githubusercontent.com/assets/8013017/9570980/eefb660a-4f96-11e5-8927-783ed76e85b5.png)

The solution above is quite easy to implement with DatePicker cells, but there may be different ways to do it with Selector cells: 
![screen shot 2015-08-31 at 04 14 33](https://cloud.githubusercontent.com/assets/8013017/9506917/3ca4e72c-4c4b-11e5-8c48-49b1c54b39d7.png)

**Comment by richardoti** [comment]
After a bit of debugging this seems to be not so easy UI-wise, as there might be different header heights, so it would not look good with standard solution (1st screenshot).

**Comment by 3lvis** [comment]
@richardoti can you sketch what you had in mind? I remember showing you the Slack for iOS semi-modal screen. We could do something like that.

**Comment by richardoti** [comment]
@3lvis what I tried to replicate is top screenshot exactly (on iPad) and default iPhone modal screen with "Done" / "Cancel" butons pair on top. 
Like this:
![simulator screen shot 28 sep 2015 06 07 41](https://cloud.githubusercontent.com/assets/8013017/10127737/4d295ad6-65a7-11e5-9b65-411f443f70ec.png)

Seems that I've even used the same dialog on both of the screenshots, which proves how the Popover should be handled on iPhone.

**Comment by 3lvis** [comment]
@richardoti You can have the navigation bar display only the "Contract Type" title. Then as UITableViewHeader have the rest of the text.

![sketch](https://cloud.githubusercontent.com/assets/1088217/10128668/baa9ec84-65b5-11e5-82c3-a8497306aed2.png)

**Comment by richardoti** [comment]
Interesting concept, I will try to implement it.

**Comment by 3lvis** [comment]
Fixed on https://github.com/hyperoslo/Form/pull/479
