### ISSUE TITLE
Group header not visible

### ISSUE THREAD

**Issue by zentraedi** [hyperoslo/Form#454]
Hi fellows. I just came across this excellent library for a project i need to develop.

I'm using Storyboards for my project and i tried setting up everything in different ways (demo way included) but my forms won't display the group header. I have two groups.

![screen shot 2015-09-03 at 17 20 18](https://cloud.githubusercontent.com/assets/1830701/9671900/1b05aa82-5260-11e5-995d-b8a0f43424d9.png)

This is the JSON file: https://gist.github.com/zentraedi/ff029254549ff968e55f

Additionally:

- Is it possible to use placeholders for fields?
- Is it possible to create buttons with images?
- Is it possible to specify size for dynamic sections?

Thanks in advance

**Comment by jeffleeismyhero** [comment]
What happens if you add a second group?

**Comment by jeffleeismyhero** [comment]
Also, when you say "placeholder for fields" are you referring to something like an empty "cell" to adjust the positioning of other fields?

**Comment by jeffleeismyhero** [comment]
I put your JSON into the Basic-ObjC demo and everything worked without issue. It could be a similar issue to this: https://github.com/hyperoslo/Form/issues/444

**Comment by richardoti** [comment]
@zentraedi Hi! I may look at this tomorrow. Seems that #444 might be related, asa @jeffleeismyhero  has pointed.

I will add storyboard demo project as well, so it would be possible for storyboard users to have an "official" reference.

**Comment by zentraedi** [comment]
There are two groups, the second one starts with the Twitter and Facebook buttons.

I meant placeholder label for fields, like the default for UITextField provided in iOS. Could be useful if anyone prefers placeholder labels instead of the label on top of the field.

**Comment by zentraedi** [comment]
Thanks @jeffleeismyhero @richardoti I'll check that out.

**Comment by zentraedi** [comment]
It worked, i managed to set the layout from the presenting view controller.

Many thanks.

**Comment by richardoti** [comment]
@zentraedi which way?Could you provide, how you solved this problem?

**Comment by zentraedi** [comment]
Sure!

I have a simple Table View Controller embedded in a Navigation View Controller, a Bar Button Item provides a modal segue to a view controller for the form, i just set up everything in prepareForSegue, like this:

```
- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)__attribute__((unused))sender
{
    if ([segue.identifier isEqualToString:@"toNewEventViewController"]) {
        NSArray *JSON = [NSJSONSerialization JSONObjectWithContentsOfFile:@"new_event.json"];
        FORMLayout *layout = [FORMLayout new];
        PRAddEventVC *addEventVC = (PRAddEventVC *)[[[segue destinationViewController] childViewControllers] objectAtIndex:0];
        [addEventVC setJSON:JSON];
        [addEventVC setLayout:layout];
        [addEventVC setManagedObjectContext:self.managedObjectContext];
    }
}
```

The modal view controller is a subclass of FORMViewController exposing an NSArray and a FORMLayout property. I override initWithJSON:andInitialValues:disabled: and then set collectionView.collectionViewLayout subsequently.

```
- (instancetype)initWithJSON:(id)JSON andInitialValues:(NSDictionary *)initialValues disabled:(BOOL)disabled
{
    self = [super initWithJSON:JSON andInitialValues:initialValues disabled:disabled];
    
    if (!self) return nil;
    
    return self;
}

- (void)setupUI
{
    self.collectionView.contentInset = UIEdgeInsetsMake(20.0f, 0.0f, 0.0f, 0.0f);
    self.collectionView.backgroundColor = [UIColor whiteColor];
    self.collectionView.collectionViewLayout = self.layout;
}
```

**Comment by richardoti** [comment]
@zentraedi I don't think that it is a good idea as it leads to tight coupling of ViewControllers. 
You may check my PR here: https://github.com/hyperoslo/Form/pull/457 , how to set up FORMViewController with storyboards. With this approach you can keep all FORM-related code at one place.
