### ISSUE TITLE
Is there any support for localization?

### ISSUE THREAD

**Issue by zentraedi** [hyperoslo/Form#455]
Hi everyone.

How can i use NSLocalizedString or any localization variant? I've searching and digging but so far i haven't found anything relevant.

Thanks in advance.

**Comment by 3lvis** [comment]
Hi Hector, you would have to either provide different JSONs for each language that you are supporting or have a base JSON structure then in your app parse this JSON and modify the text using `NSLocalizedString`. I hope this was useful :)

Btw, any ideas on how we could make this better?

Best,

**Comment by zentraedi** [comment]
I've sent a PR #456 with some modifications to support basic localization. Let me if there's anything missing...

Regards

**Comment by jeffleeismyhero** [comment]
Since #456 has been merged in, can this be closed?

**Comment by richardoti** [comment]
@jeffleeismyhero yep
