### ISSUE TITLE
Dynamically update (add, edit, insert) values to select type field

### ISSUE THREAD

**Issue by zentraedi** [hyperoslo/Form#458]
Hi everyone!

I have a select type field but haven't defined any values yet in the json file. I want to dynamically populate the field with values coming from Core Data (or a web service call). I'm using a popover in the form view controller that allows the user to add a client to the database should this client not exist, so on popover dismissal i want to reload the select field with the updated values fetched from Core Data.

Any hints as to how i can perform this?

Thanks in advance.

**Comment by richardoti** [comment]
Hi!
If I got it correctly, you're using this popover:
![3ca4e72c-4c4b-11e5-8c48-49b1c54b39d7](https://cloud.githubusercontent.com/assets/8013017/9701647/90d93ce0-5433-11e5-9d49-a33dba476bb7.png)
And one of the options is  "New user".

I may suggest few options here:
1. create new user with all the info on form submit, so you don't need to reload anything dynamically
2. Update `FORMField` of the `FORMPopoverFieldCell`, so the next time user taps on the cell the method `- (void)updateContentViewController:(UIViewController *)contentViewController withField:(FORMField *)field ` gets called and the tableview in popover will be reloaded with new data.
3. Subclass `FORMSelectFieldCell` and feed it with custom TableViewController, potentially with subclass of `FORMFieldValuesTableViewController` connected to the datasource you want - this if you want fully custom solution, but I think, 2nd option should satisfy almost all the needs.

**Comment by zentraedi** [comment]
Actually i'm using a custom popover with a FORMViewController and it works as expected.

![screen shot 2015-09-05 at 20 31 21](https://cloud.githubusercontent.com/assets/1830701/9701903/820b82de-540d-11e5-8fb6-02f049ce52ba.png)

![screen shot 2015-09-05 at 20 35 35](https://cloud.githubusercontent.com/assets/1830701/9701913/6ab10c16-540e-11e5-9705-26c03a2a64e2.png)

What i want to achieve is to update the values in this select type field. I managed to get the field by using ```fieldWithID:includingHiddenFields:```, set some test values but when i tap on the dropdown i get an error. Is there anything additional that needs to be donde to update the ```FORMPopoverFieldCell```?

Thanks

**Comment by 3lvis** [comment]
Have you tried a combination of [`fieldWithID: includingHiddenFields:completion:`](https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.h#L202-L205), adding values to the field, finally using [`reloadFieldsAtIndexPaths:`](https://github.com/hyperoslo/Form/blob/master/Source/FORMDataSource.h#L237-L241) with the returned indexPaths in the first method?

**Comment by zentraedi** [comment]
Thanks @3lvis, it worked. Problem was that i was using ```setValues:``` with a plain ```NSDictionary``` when a ```FORMFieldValue``` is needed.

I can verify that it also works without using ```reloadFieldsAtIndexPaths:```, just getting the strong pointer to the field and then setting the values.

Best,

**Comment by 3lvis** [comment]
Nice to hear that you got it working :)
