### ISSUE TITLE
Demos -  Pods Installation error

### ISSUE THREAD

**Issue by s2892** [hyperoslo/Form#459]
I try to run the demo project
when i try: 
> pod install

i have an error
> Fetching podspec for `Form` from `../../`
[!] Unable to find a specification for `NSDictionary-HYPNestedAttributes (~> 0.4.1)` depended upon by `Form

the same is happend when i try install demos via
> pod try Form

how to fix this problem ? 
Thank you for help

**Comment by 3lvis** [comment]
Hi @s2892,

Would you mind trying with the `source` on top of your Podfile? Something like this:

```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod 'Form'
```

**Comment by s2892** [comment]
i try: 
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'Form'
```
the responds is the same: 
```
Analyzing dependencies
[!] Unable to find a specification for `NSDictionary-HYPNestedAttributes (~> 0.4.1)` depended upon by `Form`
```
I have updated pod to the newest version i downloaded the git again. the same error. :(

**Comment by 3lvis** [comment]
@s2892 Looks like this is a CocoaPods bug. Please take a look at this tread.

https://github.com/CocoaPods/CocoaPods/issues/2543

Maybe using something like

```
--sources='git@our-private-spec-repo:iOS/Specs.git,https://github.com/CocoaPods/Specs'
```

Could fix your issue. I tried this search on Google too => http://lmgtfy.com/?q=%22%5B!%5D+Unable+to+find+a+specification+for%22

Good luck :)

**Comment by richardoti** [comment]
Yep, I confirm that it is cocoapod bug.
Using v 0.38.2 - fails
if I use 0.37.2 - works OK

**Comment by s2892** [comment]
yes. I pushed examples to work 
thank you :+1:
