### ISSUE TITLE
Easier way to create forms

### ISSUE THREAD

**Issue by annehiro** [hyperoslo/Form#472]
I am just beginning to use Form. The UI looks amazing but the way to create forms is extremely low level and hands on. I understand this comes with the flexibility Form provides but how come there is no API, in addition to the JSON way, to create forms? 

I think I will write my own. Am I the only one who sees a need for this or should I write it with the possibility in mind that it will be included in Form?

**Comment by 3lvis** [comment]
Hey @annehiro,

I hope you figure it out :) We're working on improving the docs. Let us know if we can help with anything/
