### ISSUE TITLE
Crash on orientation change

### ISSUE THREAD

**Issue by annehiro** [hyperoslo/Form#475]
I have Storyboard->UIViewController->Container View. The Container View is pinned to the corners of UIViewController's view in Storyboard and AutoLayout is enabled. I programmatically instantiate a subclass of FORMViewController, move it to parent VC, and then add its view to the container view.

On orientation change, it hits the first abort in fieldsAtSection:section.

**Comment by 3lvis** [comment]
There's a storyboards demo, it might help you to find some clues.

https://github.com/hyperoslo/Form/tree/master/Demos/iPhone-Storyboard

**Comment by richardoti** [comment]
@annehiro would like to check the full stack trace. If I am correct, you're using method:
`addChildViewController` ?

**Comment by annehiro** [comment]
Hey thanks for the quick response. I just had to declare the subclass of FORMViewController as a class variable instead of defining it inside a method. Its working now.

**Comment by 3lvis** [comment]
:tada:
