### ISSUE TITLE
Programmatically insert from template

### ISSUE THREAD

**Issue by annehiro** [hyperoslo/Form#478]
Is this possible? Or do I need to create the section and hide/show it instead?

**Comment by 3lvis** [comment]
@annehiro At the moment there isn't a build-in way to call the insert method but you can use a workaround. I'll add a task for your request so we can considerate it for a future update. This is taken from the unit tests code => https://github.com/hyperoslo/Form/blob/master/Tests/Tests/FORMDataSourceTests.m#L271-L303

Right you you can create a category on FORMDataSource:

```
@interface FORMDataSource ()

- (void)fieldCell:(UICollectionViewCell *)fieldCell updatedWithField:(FORMField *)field;

@end
```

```
Then find the field using `fieldWithID`, the just call `dataSource:fieldCell:updatedWithField`.
    FORMField *field = [dataSource fieldWithID:@"companies.add" includingHiddenFields:NO];
    [dataSource fieldCell:nil updatedWithField:field];
```

**Comment by annehiro** [comment]
Thank you once more :smiley:

**Comment by 3lvis** [comment]
@annehiro You're welcome! Sorry that this isn't more clear.
