### ISSUE TITLE
"Cancel" button removes date value from the field

### ISSUE THREAD

**Issue by richardoti** [hyperoslo/Form#480]
Steps to reproduce:
1 Open FORM (Basic-ObjC demo), select any date field
![screen shot 2015-10-14 at 09 34 52](https://cloud.githubusercontent.com/assets/8013017/10477592/a0a21a42-7257-11e5-8cc0-f90cb5f28c83.png)

2  Tap "Cancel"

![screen shot 2015-10-14 at 09 34 59](https://cloud.githubusercontent.com/assets/8013017/10477519/138a66a0-7257-11e5-86dc-b1bdbfc8ef26.png)

The field becomes empty, while as a user I expect it to keep previous value.

Is it a bug or expected behavior? If it is expected, I'd guess, name "Clear" would suit here better, as "Cancel" should not mutate the object in any case.

**Comment by 3lvis** [comment]
It the field had a date before you opened the date picker then cancel shouldn't do anything.

If the field was empty before you opened the date picker THEN if you press cancel, it should go blank.

**Comment by richardoti** [comment]
@3lvis that totally makes sense to me, i.e. "Cancel" should not affect the field at all, but just dismiss the popover.

I mark this as a bug and will fix in my PR.

**Comment by 3lvis** [comment]
> "Cancel" should not affect the field at all, but just dismiss the popover.

That's not correct, "Cancel" just cancels any chance that you've done to the field. Otherwise it would be called "Dismiss" but we don't need a dismiss button on the iPad since you can tap outside of the popover to dismiss.

**Comment by 3lvis** [comment]
Fixed on https://github.com/hyperoslo/Form/commit/7ccc28539f4fa7943b88e0173d2625503b0cacd2
