### ISSUE TITLE
toolbar incorrect position with hardware keyboard

### ISSUE THREAD

**Issue by jeffreyjackson** [hyperoslo/Form#481]

**Comment by 3lvis** [comment]
@jeffreyjackson I saw this in the simulator, it also happens on device?

**Comment by 3lvis** [comment]
@jeffreyjackson :)

**Comment by 3lvis** [comment]
@jeffreyjackson

**Comment by 3lvis** [comment]
@jeffreyjackson I saw this in the simulator, it also happens on device?

**Comment by 3lvis** [comment]
Closed since there wasn't a reply.
