### ISSUE TITLE
appDelegate and initCoder

### ISSUE THREAD

**Issue by ehirebrandon** [hyperoslo/Form#486]
Everything seems to be have to work through app delegate what if I want to use View controller. I've try so many ways, I can't subclass without an error and have it running.

**Comment by 3lvis** [comment]
@ehirebrandon could you share the error with us? This should work. Are you using storyboards? There's a sample project on how to do this.

https://github.com/hyperoslo/Form/tree/master/iPhone-Storyboard

**Comment by ehirebrandon** [comment]
Hi,

Yes I am trying to use storyboard. What I try to do is subclass (let's say
like a sampleViewController that subclass from FORMViewController). Then in
my view controller I try to present the an instance of the
sampleViewController however it does not work. It seems like the only way
is to go through app delegate to present the form, which works. However I
have multiple view controller that is in an array that let me slides from
one to another. However Json error/ and other random errors come up. I'm
currently using swift and I can't understand FORMViewcontroller etc, so I
only hope to subclass from it and everything work. Can you please update
with an example that have view controller that uses it without the app
delegate. The sample for iphone-storyboard is also insufficient, because it
does not provide a view controller that present it the way most other apps
do. It's quite unconventional for anyone to just use these forms as one
single view. Can you assist?

Thank you,

brandon

**Comment by 3lvis** [comment]
@ehirebrandon Here it is the demo, there's an issue with the layout's delegate, I'm not experienced on storyboards, hopefully you'll be able to fix it :)

https://github.com/hyperoslo/Form/pull/487

**Comment by 3lvis** [comment]
@ehirebrandon https://github.com/hyperoslo/Form/tree/master/ModalForm 

Here's how you do it. https://github.com/hyperoslo/Form/blob/master/ModalForm/ViewController.swift#L6-L7

You don't need to hook up anything on Interface Builder.

Make sure you apply the default style https://github.com/hyperoslo/Form/blob/master/ModalForm/AppDelegate.swift#L11
