### ISSUE TITLE
Adding sub-heading feature

### ISSUE THREAD

**Issue by RyanKim01** [hyperoslo/Form#490]
Hi
When I'm building my survery form I realized I need sub-headings if possible.
![screen shot 2015-12-17 at 2 50 00 pm](https://cloud.githubusercontent.com/assets/10735853/11884287/7c4c32ba-a4cd-11e5-8e5a-909566c1ddaa.png)

For example, "Part1. Petitioner Information" is a heading
and (1) (legal name of individual petitioner) is sub-heading. And Family name, Given name, Middle name are different names of fields. Would there be any way I can make a sub-heading without textfields below?

**Comment by jeffleeismyhero** [comment]
At one point I was looking to do something similar. My recommendation would be to create a custom form element. That process is outlined here: https://github.com/hyperoslo/Form/pull/8

**Comment by RyanKim01** [comment]
@jeffleeismyhero , I'm currently taking a look at custom field class. https://github.com/hyperoslo/Form/blob/master/CustomField/CustomField.swift
So I completely took out textview but it still leaves the big chunk of space. Can you guess why this is happening? I literally just commented out "self.addSubview(self.textView)"

![screen shot 2015-12-17 at 10 04 07 pm](https://cloud.githubusercontent.com/assets/10735853/11890519/1ef95434-a50a-11e5-9e0d-816a39579ea5.png)

**Comment by 3lvis** [comment]
@RyanKim01 The blank space is where you are supposed to add your content.

**Comment by 3lvis** [comment]
I think maybe we could add a new field to form to handle this cases, it will be a UITextView, it will allow HTML and internally that HTML will translate to NSAttributedStrings.

At the moment I don't have enough time to do the change, but feel free to add this if you're interested :heart: 

A workaround would be to do what @jeffleeismyhero mentioned. From what I see you are in the right steps.

**Comment by RyanKim01** [comment]
@3lvis I will definitely look into it and will write here again if I can get to tackle it successfully :)
But for now, I will go with a way as @jeffleeismyhero  mentioned.
1. In CustomField class, I deleted ""self.addSubview(self.textView)"".
2. In forms.json file, I changed the height of "textye" from 2 to 0.3.
{
                    "id":"textye",
                    "type":"textye",
                    "size":{
                    "width":100,
                    "height":0.3
                    }
}

The result I got is like below:
![screen shot 2015-12-18 at 2 17 55 am](https://cloud.githubusercontent.com/assets/10735853/11894664/95c4283c-a52d-11e5-9620-9b1f1fe1f17d.png)


As you can see from the image, there is a grey line under "Custom Field." I've looked into classes to figure out what is causing this line but I could not figure out. Any thoughts? One thing I know that grey line is responsive to "width" value in forms.json.

**Comment by 3lvis** [comment]
The line gets added at the end of each section. It's a section separator.

https://github.com/hyperoslo/Form/blob/master/Source/FORMSeparatorView.h

**Comment by jeffleeismyhero** [comment]
You can also style that specific instance of the separator from the JSON file by setting `separator_color`.

@3lvis did the transparency addition to Hex get pulled in here as well? If so, you should be able to use `@"FFFFFF00"` to make the separator transparent. This would help in cases of a textured background or where an image is used for the background.

**Comment by 3lvis** [comment]
@jeffleeismyhero yep, current version of Form is using [Hex 3.0.0](https://github.com/3lvis/Hex).

**Comment by RyanKim01** [comment]
Thank you guys for helping me out! @jeffleeismyhero  I do not know why but adding "separator_color":"#FFFFFF" did not change the color. So I just added the method what @3lvis  mentioned above in CustomField class and it worked.

**Comment by 3lvis** [comment]
@RyanKim01 I'm glad you made it work, have a great weekend!
