### ISSUE TITLE
Changing number of lines in headingLabel

### ISSUE THREAD

**Issue by RyanKim01** [hyperoslo/Form#491]
I am having an issue with fitting long sentence in a heading label.
Since headinglabel is subclass of UILabel, I was manipulating it with UILabel's properties.
In Overried init method in CustomField class, I inserted
         self.headingLabel.text = "Custom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom FieldCustom"
        self.headingLabel.numberOfLines = 0

If I set the numberOfLines as 0 it should return all texts of the label. But it only returns one sentence. Please refer to the image below.
![screen shot 2015-12-18 at 12 44 29 pm](https://cloud.githubusercontent.com/assets/10735853/11906948/1b30cfe6-a585-11e5-866d-ce0d4c5537e3.png)

Is Form framework disabling multiple lines in headingLabel at somewhere? Any thoughts?

**Comment by 3lvis** [comment]
By default this one is one line and it's not customizable :cry:

**Comment by RyanKim01** [comment]
@3lvis Oh bummer. If I'm trying to input multiple lines of instructions to fill out the form, then should I just add multiple one-line sentences? Would changing this setting impact the layout significantly?

**Comment by 3lvis** [comment]
I added an example on how you could achieve what you want. https://github.com/hyperoslo/Form/pull/492

**Comment by RyanKim01** [comment]
@3lvis Thank you!
