### ISSUE TITLE
Problem when keyboard hides

### ISSUE THREAD

**Issue by costantino78** [hyperoslo/Form#493]
Hi.
In my app I have a ViewController hooked to a controller in soryboard that loads the form as follows:

    override func viewDidLoad() {
        super.viewDidLoad()
        let formController = SampleCollectionViewController()
        addChildViewController(formController)
        //formController.view.frame = self.view.bounds
        self.view.addSubview(formController.view)
    }

where SampleCollectionViewController is a subclass of FORMViewController. When the application starts it's all right, as you can see from the first image, but if I compile any filed, when the keyboard hides the form is repositioned from top of the frame, and not under the navigation bar. How can I fix?

Sorry for the question, but I'm new in iOS programming.
Thank you

##### Image 1. Start app, it's ok, there is a space between navigation controller and form, defined with self.collectionView?.contentInset = UIEdgeInsets(top: 20, left: 0, bottom: 0, right: 0) in viewDidLoad of SampleCollectionViewController class.

![image1](https://cloud.githubusercontent.com/assets/2123837/11918971/7ce0b6fa-a744-11e5-9740-b9666e5c3f3d.PNG)

##### Image 2. I write something

![image3](https://cloud.githubusercontent.com/assets/2123837/11918974/7d15d20e-a744-11e5-8483-34691a14e136.PNG)

##### Image 3. When keyboard hides, the form is covered by navigation control.

![image2](https://cloud.githubusercontent.com/assets/2123837/11918972/7d0755f8-a744-11e5-99af-ceabc7fe7e8a.PNG)

##### Image 4. My navigation controller and UIViewController.

![image4](https://cloud.githubusercontent.com/assets/2123837/11918973/7d0e6654-a744-11e5-949e-7ec3495e28c1.png)

**Comment by 3lvis** [comment]
Hi @costantino78, I'm sorry I can't be helpful, this doesn't seem to be a Form bug, but more a UIKit/ViewController containment bug.

**Comment by richardoti** [comment]
@costantino78 
```Swift
override func viewDidLoad() {
    super.viewDidLoad()
    self.edgesForExtendedLayout = UIRectEdge.None
/.../
}
```
