### ISSUE TITLE
Getting rid of white gap area

### ISSUE THREAD

**Issue by RyanKim01** [hyperoslo/Form#495]
Please look at this image first.
<img width="356" alt="screen shot 2015-12-31 at 10 43 45 am" src="https://cloud.githubusercontent.com/assets/10735853/12067248/79d012de-afab-11e5-8c84-2ae48d82b5bf.png">
As you can see, there is a big white gap between my customfield and select type. I was trying a lot to get rid of it, but I could not figure out.

Here is a json format:
![screen shot 2015-12-31 at 10 43 38 am](https://cloud.githubusercontent.com/assets/10735853/12067253/9d7ae8d0-afab-11e5-97b4-c8a653c56dc9.png)

Here is a custom field class:
![screen shot 2015-12-31 at 10 42 43 am](https://cloud.githubusercontent.com/assets/10735853/12067255/a703a2ca-afab-11e5-934b-e73ab3ade969.png)

I played with changing value for height, but that did not work. Any advices would be appreciated. And Happy new year!

**Comment by 3lvis** [comment]
Like this https://github.com/hyperoslo/Form/pull/497 ?

**Comment by RyanKim01** [comment]
Feels bad that I could not figure that out :/ thank you always @3lvis !
