### ISSUE TITLE
Custom cells leaving small mark of separator line 

### ISSUE THREAD

**Issue by RyanKim01** [hyperoslo/Form#498]
In my form, I would like to keep the default separator line. However, I do not want it for my custom fields.
I have a custom fields which only has a textview.

Here is an issue I'm having (you can see small line of separator on the sides):
<img width="569" alt="screen shot 2016-01-01 at 4 00 38 pm" src="https://cloud.githubusercontent.com/assets/10735853/12072680/a8306c9a-b0a1-11e5-8b4e-a6f418f01a20.png">

Things I tried:
(1) I try setting separator line as whitecolor but it ends up erasing all other separator lines I need in the form. Code is like below:
![screen shot 2016-01-01 at 4 08 04 pm](https://cloud.githubusercontent.com/assets/10735853/12072684/ecd6f67a-b0a1-11e5-8e5c-a25d4081a99e.png)

(2) I tried using styling format in JSON like below but that did not work either:
![screen shot 2016-01-01 at 4 04 29 pm](https://cloud.githubusercontent.com/assets/10735853/12072687/fdb2b3e4-b0a1-11e5-89dc-a89138e05c5e.png)

Do you think there is a way to remove one separator line in a custom field without overriding other separator lines?

**Comment by 3lvis** [comment]
Are you using Form — 3.8.0?

**Comment by RyanKim01** [comment]
@3lvis Didn't know a new version was out. Just did pod update and it works fine. Closing this issue. Thank you!

**Comment by 3lvis** [comment]
Woho! :tada:
