### ISSUE TITLE
Add support for making more complex fields

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/Form#499]
<img width="994" alt="f0cc6542-b0d5-11e5-8312-5a1210d09d92" src="https://cloud.githubusercontent.com/assets/1088217/12074185/e56d41e6-b146-11e5-8020-7d2698271e6b.png">

This could be achieved by:

- [ ] Having a field that only displays text
- [ ] Adding support for removing the title from fields

**Comment by 3lvis** [comment]
First seen in https://github.com/hyperoslo/Form/pull/497#issuecomment-168367628

**Comment by RyanKim01** [comment]
@3lvis  Do you think making a title of a field multiline would solve this problem? 
Plus, is it possible to make textfield in FORMField make multilines so it looks like Biography custom field?

**Comment by 3lvis** [comment]
None of this ones are supported in Form at the moment. But adding them shouldn't be that complicated.

**Comment by 3lvis** [comment]
Making the title multiline could work. The only issue is that adding support for resizable titles is going to be a bit more challenging. Also it wouldn't allow the type of Form that we have here. Where it has checkboxes and a text field.

**Comment by 3lvis** [comment]
Closing this one for now since it would require major architectural changes. Let's reconsider once the bugs have been fixed.
