### ISSUE TITLE
Keyboard type

### ISSUE THREAD

**Issue by DataGlance** [hyperoslo/Form#509]
Would it be possible to default Keyboard type to Number Pad for some field types like _number_ and _count_?

**Comment by 3lvis** [comment]
Hi @DataGlance, Although that's probably not going to work on iPad since you don't have a Number Pad there.

**Comment by DataGlance** [comment]
That is correct but UIKeyboardTypeNumberPad is designed for numeric entry on the iPad too. The regular keyboard will not have the number keys at the top row.

**Comment by jeffleeismyhero** [comment]
Ideally, the keyboard could be adjusted via JSON parameters. That way, you could set any of the fields to whatever keyboard was appropriate.

@3lvis: If this is something that you'd merge in, I can add it and submit a PR.

**Comment by 3lvis** [comment]
I think would be better to as @DataGlance mentioned, ensure that `number` and `count` show the right keyboard type.

**Comment by 3lvis** [comment]
You have to set the `input_type` to `number` in the JSON file.

![simulator screen shot jun 23 2016 10 59 39 pm](https://cloud.githubusercontent.com/assets/1088217/16320058/2e397a52-3996-11e6-8e99-eda8de1feee2.png)

**Comment by 3lvis** [comment]
I have changed the code to use the field type as input type if an input type is not provided.

https://github.com/hyperoslo/Form/pull/528
