### ISSUE TITLE
FORMFloatInputValidator floatSet 

### ISSUE THREAD

**Issue by aminiz** [hyperoslo/Form#512]
Should we not be using a dot as the decimal point instead of comma? 
I am referring to the line 
`    NSCharacterSet *floatSet = [NSCharacterSet characterSetWithCharactersInString:@"1234567890,"];`

**Comment by 3lvis** [comment]
Hi @aminiz,

This is our fault, we were using the norwegian locale for this element. That's why we used `,` as decimal separator but I understand you would like to use `.` instead.

Do you have a suggestion on how we could improve this?

Thanks <#

**Comment by aminiz** [comment]
Ah right, there are iOS developers outside the US too. Hard to remember when you live in Silicon Valley. 

Do you think we could use NSLocaleDecimalSeparator instead?

**Comment by 3lvis** [comment]
@aminiz that could work too, would you mind giving it a try?

**Comment by aminiz** [comment]
Yes, let me try (:

**Comment by aminiz** [comment]
Addressed in #521
