### ISSUE TITLE
Auto show keyboard

### ISSUE THREAD

**Issue by aminiz** [hyperoslo/Form#514]
Is there a simple way to automatically select the first text field on viewDidAppear? I also want to change the Done button to Next and jump from one text field to the next that way. I have been digging through FORM code but cannot figure it out. Thanks!

**Comment by 3lvis** [comment]
Hi @aminiz,

You could keep a reference to the first cell, in the `FORMConfigureCellBlock`. Then in view did appear you could find the `textField` and use `becomeFirstResponder`.

Regarding jumping to the next field it will need some work in the internals of Form. Feel free to submit a PR with this feature <3
