### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by n8stowell82** [hyperoslo/Form#515]
Hi I have an obj-c project that I am working on updating to swift.  however in the meantime, I have some pods that are really not playing nice with the `use_frameworks!` flag.  Obviously your project requires this, but is causing serious compiler errors when enabling frameworks in cocoa pods.  I am now trying to switch new swift related dependencies to use carthage so that I can minimize the effects of the `use_frameworks` flag.

All that being said, to ask if there is anyway you could offer carthage support? or drop the "hex" requirement so that `use_frameworks` is no longer needed?  thanks

**Comment by 3lvis** [comment]
Hi Nathan,

I would love to add Carthage support for this. I'm going to figure out the best way to do it, since it's quite some work.

Btw, how did you figured out that the `Hex` dependency is the only one that could be removed before you can remove `use_frameworks`?

**Comment by 3lvis** [comment]
Hi Nathan,

I tried removing the Hex dependency and building without using `use_frameworks!` turns out it needs a few more changes than that, and it also breaks Swift projects.

In the meantime you can do

```ruby
pod 'Form', git: 'git@github.com:hyperoslo/Form.git', branch: 'remove-hex-dependency'
```

**Comment by n8stowell82** [comment]
@3lvis wow thank you so much for the quick response!  To be honest I narrowed in on Hex as it is what cocoapods yells at me for when I try to install without having use_frameworks! enabled.  I will give the new branch a shot and I hope that works short term.   I think the better solution is of course carthage support.  it lets me sidestep all of this `use_frameworks!` nonsense.  I am starting to sour on cocoapods pretty badly these days :(

Thanks again for your quick response and eagerness to help!

**Comment by 3lvis** [comment]
I would love to have Carthage support but it's a lot of work, since we will have to update each dependency to have Carthage standards. If you have time feel free to try! <3

**Comment by n8stowell82** [comment]
absolutely! I will see what I can get done.  would I need to submit a pull request for each repo?

**Comment by 3lvis** [comment]
@n8stowell82 yeah I started doing it in some repos but it's a lot of work.

Check https://github.com/3lvis/Networking for an example
