### ISSUE TITLE
Placeholder text in textfield

### ISSUE THREAD

**Issue by aminiz** [hyperoslo/Form#517]
Is it possible to pass a placeholder text to text field cell or should we create a custom cell that looks the same?

**Comment by 3lvis** [comment]
I'm not sure if I get what you mean, did you meant having a way to set the placeholder to a textfield?

**Comment by aminiz** [comment]
Correct. I would like to pass a placeholder text to formField of type text

**Comment by 3lvis** [comment]
Available on [Form `3.10.0`](https://github.com/hyperoslo/Form/releases/tag/3.10.0)
