### ISSUE TITLE
Automatically select a textField

### ISSUE THREAD

**Issue by aminiz** [hyperoslo/Form#520]
On viewDidAppear, I want to call becomeFirstResponder on the first FORMField (type text). Is this currently possible?

**Comment by aminiz** [comment]
Let me clarify a little. I have a simple login form that allows the user to enter a username and password. When the form appears, I want to auto select `Username` textField and popup the keyboard. The keyboard `Return Key` should be set to `Next`. When the user presses `Next`, I want to select `Password` textField and change `Return Key` to `Go`. When the user presses `Go`, I want to call a method. 

Is this something that is currently possible or perhaps something you could see fitting into the Form design? I am glad to help with any implementation if needed.

**Comment by 3lvis** [comment]
I'm sorry we haven't been more responsive to some issues. It's hard to keep up with this project since it has been in maintenance mode and not many new things are happening.

**Comment by aminiz** [comment]
No worries Elvis. Thank you for creating this amazing library.
If you have some time, can you tell me your suggestion to accomplish this? I can do the implementation  myself. I might just need some guidance.

**Comment by 3lvis** [comment]
You can find the FORMField using FORMDataSource, then find the cell for the FORMField, finally in the cell you'll find the FORMTextField, there you can ask to `becomeFirstResponder`.
