### ISSUE TITLE
Reset to JSON defaults 

### ISSUE THREAD

**Issue by jeffleeismyhero** [hyperoslo/Form#524]
Presently, the `reset` method in FORMDataSource sets all values to nil. Do we have a way of resetting to the default values provided in the JSON?

**Comment by 3lvis** [comment]
@jeffleeismyhero Hi Jeffrey, currently we don't have such functionality. As you can see, values are only introduced to the FORMData values dictionary and then they get forgotten. You could easily store this values for later usage and have a method like `restoreToInitialValues` or just `restore`.

**Comment by 3lvis** [comment]
I remember we also stored the initial values in a dictionary and when the `Reset` button was pressed, we should send this values to `reloadWithDictionary`.

**Comment by 3lvis** [comment]
I think this issue might be fixed, please @jeffleeismyhero scream if this is incorrect.
