### ISSUE TITLE
Can't run this task...whit cocoapods error info...

### ISSUE THREAD

**Issue by ganjmeng** [hyperoslo/Form#525]
Can't run this task...whit cocoapods error info...
![image](https://cloud.githubusercontent.com/assets/12026835/16261791/893a8132-389f-11e6-82ba-c496cd4bb09e.png)

**Comment by ganjmeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12026835/16261812/a50a4f0a-389f-11e6-8c0f-7027e6c7aeae.png)

**Comment by 3lvis** [comment]
@ganjmeng just do

```
Pod 'Form'
```

Instead of 

```
Pod 'Form', path: "."
```

**Comment by ganjmeng** [comment]
Thanks!
