### ISSUE TITLE
Is there a way to get the JSON result of filled form?

### ISSUE THREAD

**Issue by alexliubj** [hyperoslo/Form#530]
Hi folks, 

For e.g, I fill the form with textfield and selection and some other controls and then I want to export this form result as a JSON string, how I can get it?

Thanks,

**Comment by 3lvis** [comment]
Hi, use `dataSource.values`

https://github.com/hyperoslo/Form#how-do-i-get-all-the-values-of-the-form

**Comment by alexliubj** [comment]
Thanks, I saw that but I thought it should be static original value but I was wrong.

**Comment by jeffleeismyhero** [comment]
To expand a little on what @3lvis linked to, `dataSource.values` will return an NSDictionary so you'll need to convert it to JSON separately.

**Comment by 3lvis** [comment]
Good point, @jeffleeismyhero.

**Comment by alexliubj** [comment]
Wait, actually I check it again. `dataSource.values` is not what I want.
I want the original forms.json as well as the values filled but not only the one with values in the dictionary.

Thanks,
