### ISSUE TITLE
Feature Request: Spacer fields

### ISSUE THREAD

**Issue by jeffleeismyhero** [hyperoslo/Form#531]
To expand on interface flexibility, I'd like to build a "spacer" field. The purpose of this would be to partition the form for readability and data isolation.

![simulator screen shot aug 12 2016 5 55 26 pm](https://cloud.githubusercontent.com/assets/43980/17639264/1eaba8f2-60b6-11e6-8f9b-155d91c6b8cd.png)

This example is somewhat contrived, but I think this functionality can be useful. Would this be something that you would want in Core, or as a separate module? If separate, is there a framework for doing so?

**Comment by 3lvis** [comment]
Hi @jeffleeismyhero,

Just to be sure. Are you talking about this spaces?

![group](https://cloud.githubusercontent.com/assets/1088217/17641527/0cd2ee74-6124-11e6-8d29-05ce1f121695.png)

**Comment by jeffleeismyhero** [comment]
Yes, that's correct.

**Comment by jeffleeismyhero** [comment]
It could be very useful for buttons too: 

![simulator screen shot aug 13 2016 12 00 02 pm](https://cloud.githubusercontent.com/assets/43980/17644504/a32af302-614d-11e6-99ea-f344fbe1504f.png)

**Comment by 3lvis** [comment]
I see how this could be achievable but I don't see how that would be a good way to separate files, isn't this what you really want?

![group](https://cloud.githubusercontent.com/assets/1088217/17647461/6f058a02-61f1-11e6-93dc-0dce4bae924d.png)

**Comment by jeffleeismyhero** [comment]
The goal is to have more control over field placement on the line. It may be better to have the ability to specify field margins. So you could say "skip 60 units and then insert this 40 unit field." Which would effectively right align a 40 unit field. 

Or you might want to say place this 20 unit field, then place this 40 unit field with 20 units of padding to the left and 20 units of padding on the right.

Thoughts?

**Comment by jeffleeismyhero** [comment]
That photo just loaded for me. I think that is a great idea as well, but would still like more control within each group.

**Comment by 3lvis** [comment]
Go for your original approach! Let me know if you need any help. :pray

**Comment by jeffleeismyhero** [comment]
Merged in on #534 and released on https://github.com/hyperoslo/Form/releases/tag/3.11.0
