### ISSUE TITLE
the backgroundcolor is black

### ISSUE THREAD

**Issue by skarctop** [hyperoslo/Form#533]
This is normal at demo (my test demo), but in other application backgroundcolor is black  

![Simulator Screen Shot Sep 1, 2016, 1.36.22 PM.png](https://ooo.0o0.ooo/2016/09/01/57c7bede94a7b.png)

**Comment by 3lvis** [comment]
Maybe you need to set the color?
https://github.com/hyperoslo/Form/blob/master/Basic-Swift/SampleCollectionViewController.swift#L19

Would you mind providing the JSON file? Something is probably missing.

**Comment by 3lvis** [comment]
Thanks 😅
