### ISSUE TITLE
Feature Request: Segmented Control / Switch Field

### ISSUE THREAD

**Issue by jeffleeismyhero** [hyperoslo/Form#536]
Re: #474 and #476

A solution for booleans and an alternative for select fields can be very helpful - especially for one or two options. Both scenarios can be resolved with a UISegmentedControl based solution.

<img width="369" alt="screen shot 2016-09-05 at 5 42 45 pm" src="https://cloud.githubusercontent.com/assets/43980/18257852/39d49ed0-7390-11e6-8ca4-f4384d27e407.png">
<img width="150" alt="screen shot 2016-09-05 at 5 44 27 pm" src="https://cloud.githubusercontent.com/assets/43980/18257866/76a4288a-7390-11e6-9374-bc801f6dfdea.png">

I'm happy to tackle this next week if you'll have it.

**Comment by 3lvis** [comment]
![ios-7-style-smooth-toggle-buttons-with-jquery-css3-checkable](https://cloud.githubusercontent.com/assets/1088217/19250799/93cbbffa-8f3c-11e6-9e75-909bd7f0bab5.jpg)

**Comment by 3lvis** [comment]
Why not that one instead?

**Comment by jeffleeismyhero** [comment]
Ideally, I'd like to add support for UISwitch as well. In the meantime, UISegmentedControl fields are versatile enough to handle the UISwitch use-cases AND work well with FORM's width-based sizing.

Additionally, UISegmentedControl fields can support more than yes/no based selections.

**Comment by 3lvis** [comment]
Makes sense. I guess we'll keep the Switch issues open and offer this as a workaround.
