### ISSUE TITLE
how to make the rounded of field

### ISSUE THREAD

**Issue by skarctop** [hyperoslo/Form#537]
how to add rounded like this:    
![image](https://cloud.githubusercontent.com/assets/1088217/10798419/d46a4344-7da7-11e5-85b6-80df75cd5209.png)

**Comment by 3lvis** [comment]
Hi! 👋 

You have to do it using FORMTextField's appearance. Something like this.

```objc
    [[FORMTextField appearance] setFont:[UIFont fontWithName:@"Futura-Medium" size:15.0]];
    [[FORMTextField appearance] setTextColor:[[UIColor alloc] initWithHex:@"000000"]];
    [[FORMTextField appearance] setBorderWidth:2.0f];
    [[FORMTextField appearance] setBorderColor:[[UIColor alloc] initWithHex:@"FFFFFF"]];
    [[FORMTextField appearance] setCornerRadius:20.0f];
```

For the full file of the screen you're showing check here:

https://github.com/hyperoslo/Form/blob/master/Payment/FORMCustomStyle.m
